import type { ContentItem, DisplaySettings } from '../types/firestore';

export const mockContentItems: ContentItem[] = [
  {
    id: '1',
    org_id: 'default-org',
    type: 'announcement',
    title: 'Tervetuloa uuteen lukukauteen!',
    body: 'Eduro toivottaa kaikki opiskelijat ja henkilökunnan tervetulleeksi. Muistathan tarkistaa uudet turvallisuusohjeet intrasta.',
    media_url: null,
    media_type: 'none',
    event_date: null,
    start_time: null,
    end_time: null,
    location: null,
    qr_url: null,
    publish_start: new Date().toISOString(),
    publish_end: null,
    duration_seconds: 15,
    is_published: true,
    is_archived: false,
    sort_order: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'mock',
    updated_by: 'mock'
  },
  {
    id: '2',
    org_id: 'default-org',
    type: 'media',
    title: 'Hae nyt syksyn koulutuksiin',
    body: 'Tarjoamme laajan valikoiman täydennyskoulutuksia IT-alalle. Katso tarjonta ja hae mukaan.',
    media_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1000',
    media_type: 'image',
    event_date: null,
    start_time: null,
    end_time: null,
    location: null,
    qr_url: null,
    publish_start: null,
    publish_end: null,
    duration_seconds: 10,
    is_published: true,
    is_archived: false,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'mock',
    updated_by: 'mock'
  }
];

export const mockSettings: DisplaySettings = {
  id: '1',
  org_name: 'Eduro',
  welcome_text: 'Tervetuloa Eduroon!',
  rotation_interval_seconds: 15,
  show_announcements: true,
  show_events: true,
  show_highlights: true,
  show_qr_links: true,
  show_opening_hours: true,
  opening_hours_text: 'Ma-Pe 08:00 - 16:00',
  fallback_message: 'Ei uusia tiedotteita tällä hetkellä. Mukavaa päivää!',
  logo_url: null,
  show_weather: true,
  weather_lat: 66.5039,
  weather_lon: 25.7294,
  weather_location_name: 'Rovaniemi',
  accent_color: '#4f46e5',
  theme: 'dark',
  updated_at: new Date().toISOString(),
};
